[package]
name = "amd-smu-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "amd-smu-tui"
path = "src/main.rs"

[dependencies]
amd-smu-lib = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
