[package]
name = "amd-smu-lib"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
byteorder = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tempfile = "3"
